version: '3'
services:
  jenkins:
    build: ./jenkins
    ports:
     - "8080:8080"
    environment:
     - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
  influx:
    image: "influxdb"
    ports: 
      - "8086:8086"
  grafana:
    image: "grafana/grafana"
    ports: 
      - "3000:3000"